### ISSUE TITLE
textures crash the program

### ISSUE THREAD

**Issue by zturtledog** [electronstudio/jaylib#34]
when you use loadTexture or LoadTextureFromImage it crashes the program instantly

error:

\# A fatal error has been detected by the Java Runtime Environment:
\#
\#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=11408, tid=17568

then it prints out a file containing heap and stack info

[hs_err_pid13004.log](https://github.com/electronstudio/jaylib/files/9066269/hs_err_pid13004.log)
.

**Comment by zturtledog** [comment]
[src.zip](https://github.com/electronstudio/jaylib/files/9087547/src.zip)

this my src,

i am on java 17.

**Comment by zturtledog** [comment]
[all.zip](https://github.com/electronstudio/jaylib/files/9087923/all.zip)

i use the redhat for vscode extension to compile and run.

**Comment by electronstudio** [comment]
OK, it's pretty simple.

First this probably isn't the problem, but I had to change line 21 of cog.java to ` Texture cog0d0 = LoadTexture("src/reasource/clockworkicon.png");` in order to get the program to compile.

The actual problem is In raylib you can't call *any* functions before you've called InitWindow.  Currently you are trying to create a cog, which loads a texture, and you are doing this before InitWindow.  You would have to change it to something like
```
        InitWindow(w, h, title);
        cogtest = new cog(10, 12, 0);
```

**Comment by electronstudio** [comment]
if you have any more raylib programming questions you'd probably be better asking them in the raylib discord chat.

**Comment by zturtledog** [comment]
thanks
