### ISSUE TITLE
The need to .close() colours

### ISSUE THREAD

**Issue by glowiak** [electronstudio/jaylib#45]
For some reason, the Raylib.Color class is treated as a resource, and thus needs to be closed.

Why is that?

Shouldn't it be treated by the garbage collector, just like any other class?

**Comment by electronstudio** [comment]
All of the Raylib struct classes implement Autoclosable, not just Color. Implementing Autoclosable does not mean you must close them. 

As for what happens if you do close them, you would need to check with JavaCPP, but I assume it releases the native memory allocated by the struct.  

C structs are not stored on the garbage collected Java heap, they are stored on the native heap.

**Comment by electronstudio** [comment]
If you’re worried what happens if you don’t close() them yourself, I expect that when the object is GCed there is a finalize() method that calls close().

**Comment by glowiak** [comment]
Good. I removed the .close()'s from my code, and there was no performance decrease, despite colours being created on each frame.

**Comment by glowiak** [comment]
I asked because Eclipse gives a warning that it should be closed.

**Comment by electronstudio** [comment]
It’s best not to create objects every frame. Maybe use an object pool.

**Comment by electronstudio** [comment]
Different program but similar issue, I notice you are calling malloc and sprintf in your main loop here, which might explain why your C benchmark is slower than some of the others https://codeberg.org/glowiak/rl-bunnymarks/src/branch/master/c/bunny.c
