### ISSUE TITLE
add: rlights.h implentation for jaylib 

### ISSUE THREAD

**Issue by akashKarmakar02** [electronstudio/jaylib#53]
i was trying to make a hobby project using jaylib and needed some lighting i did the shader part and try to find create light but does not find it.

- Adding rlight.
- I am willing to help though i am not a game dev but i done jni using javacpp previously if given some instruction i do think i can help

**Comment by electronstudio** [comment]
rlights.h isn't part of the raylib library, it's a small header included in some of the raylib shader example programs.  It's only about 30 lines of code.  So it wouldn't make sense to compile the C version into Jaylib.  What would make sense is to port the C header and the C examples to Java.  (Sadly we have very few examples because no-one has volunteered to port any.)  So if you want to do that, go ahead.

**Comment by electronstudio** [comment]
It turned out to be more complicated than I expected, therefore I did it for you.

https://github.com/electronstudio/jaylib-maven-example-project/blob/master/src/main/java/examples/RLights/Light.java

https://github.com/electronstudio/jaylib-maven-example-project/blob/master/src/main/java/examples/ShadersBasicLighting.java

(due to the need to allocate arrays and maintain pointers to them to give to the shader, and also the byte conversions for the colors the shader needed)

**Comment by electronstudio** [comment]
You're welcome, don't mention it.
